### ISSUE TITLE
Readme Typo

### ISSUE THREAD

**Issue by mvirnoche** [akiojin/decode-base64-github-action#38]
Hello,

I stumbled upon your file and when I went to use your example, I found you have a typo in one section
- https://github.com/akiojin/decode-base64-github-action/blob/ede4b5ee0fdfa2e6160a70cff9f925f40a6653fe/README.md?plain=1#L46

I believe that line should match this one
- https://github.com/akiojin/decode-base64-github-action/blob/ede4b5ee0fdfa2e6160a70cff9f925f40a6653fe/README.md?plain=1#L10

**Comment by akiojin** [comment]
@mvirnoche 
Thank you for your report.
We have corrected the problem.
